custom: https://www.paypal.com/cgi-bin/webscr?cmd=_donations&item_name=NoScript+development+support+donation&item_number=freenoscript&page_style=NoScript&no_shipping=1&no_note=1&cn=Comments&currency_code=EUR&tax=0&bn=PP-DonationsBF&lc=RU&submit.x=34&submit.y=32&business=g.maone%40informaction.com
custom: https://flattr.com/@ma1/domain/noscript.net
